# What are MLM and Why do I care?



```{block type='rmdconstruct', echo=TRUE}
This chapter is **UNDER CONSTRUCTION**, so check back often.  
```





### John Nezlek

John Nezlek is currently a professor at SWPS University of Social Sciences and Humanities in Poznań Poland and the Department of Psychological Sciences, College of William and Mary (Emeritus). He divides his time between Poland and the US. John does research in Personality Psychology, Psychometrics, and Social Psychology. Much of his research concerns daily experience. He recently received a grant to study vegetarianism as a social identity


Nezlek, J. B. (2012). Multilevel modeling for psychologists. In H. Cooper, P. M. Camic, D. L. Long, A. T. Panter, D. Rindskopf, & K. J. Sher (Eds.), APA handbook of research methods in psychology, Vol. 3. Data analysis and research publication (pp. 219–241). American Psychological Association. [DOI: 10.1037/13621-011](https://doi.org/10.1037/13621-011)


* [Full PDF online](https://jbnezl.people.wm.edu/Reprints/2012-APA-Handbook-MLM.pdf)



## GEE

> The GEE method is an extension of the Generalized Linear Model (GLM) of Nelder and Wedderburn (1972) to enable correlated data be analyzed appropriately.  Repeated measures on an individual in a longitudinal study are likely to be correlated because of the continuity of the measurement over time (Burger et al., 2000). In analyzing longitudinal data using the GEE method, a working correlation structure is formulated to incorporate the possible correlations among the response observations measured at different occasions during follow-up for each individual. Formulation of the working correlation structure depends on the degree of correlation perceived among an individual’s response observations, resulting in the use of such common covariance matrix functions as the so-called independent, exchangeable, autoregressive, stationary, non stationary, and general unstructured model. Correctness of the specification of the working correlation structure is not so important in a GEE analysis because the resulting regression coefficient estimators are still consistent even when the working correlation structure is mis-specified to some extent (Liang and Zeger, 1986).
